### ISSUE TITLE
Scenario.runTape not failing on exception (with workaround)

### ISSUE THREAD

**Issue by petersgrandadventure** [holochain/holochain-rust#1034]
I'm working on making a new type called challenges, so I'm copying an existing test and adapting it to how I expect to use the object. I'm expecting it to fail because it's not fully created yet.

```
scenario.runTape('Can create a challenge with some members', async (t, {alice}) => {
    const register_result = await alice.callSync('event', 'register', {name: 'alice', avatar_url: ''})
    console.log(register_result)
    t.true(register_result.Ok.includes('alice'))
    const create_result = await alice.callSync('event', 'create_challenge', {...testNewChallengeParams, public: false, initial_members: [register_result.Ok]})
    console.log(create_result)
    t.deepEqual(create_result.Ok.length, 46)
})
```

I expect that running hc test will run all of the tests, reporting a pass for all of the existing tests and a fail for my new test.
Actual results: Running hc test throws an exception and never finishes
```
# Can create a challenge with some members
Reading DNA from dist/bundle.json
Starting instance "alice"...
{ Ok:
   'alice-----------------------------------------------------------------------------AAAIuDJb4M' }
ok 14 should be truthy
Exception occurred while calling zome function:  unable to call zome "event" function "create_challenge": InternalFailure(Dna(ZomeFunctionNotFound("Zome function \'create_challenge\' not found in Zome \'event\'")))
```
To work around this, I've added a try/catch around the test and explicitly fail the test, reporting the exception along with test failure.
```
scenario.runTape('Can create a challenge with some members', async (t, {alice}) => {
  try {
    const register_result = await alice.callSync('event', 'register', {name: 'alice', avatar_url: ''})
    console.log(register_result)
    t.true(register_result.Ok.includes('alice'))
    const create_result = await alice.callSync('event', 'create_challenge', {...testNewChallengeParams, public: false, initial_members: [register_result.Ok]})
    console.log(create_result)
    t.deepEqual(create_result.Ok.length, 46)
  } catch (err) {
    t.fail(err.message);
  }
})

---

Exception occurred while calling zome function:  unable to call zome "event" function "create_challenge": InternalFailure(Dna(ZomeFunctionNotFound("Zome function \'create_challenge\' not found in Zome \'event\'")))
not ok 15 (unnamed assert)
  ---
    operator: fail
    at: scenario.runTape (D:\holochain\dev-camp-playground\day2\dna-src\test\index.js:115:7)
    stack: |-
      Error: (unnamed assert)
          at Test.assert [as _assert] (D:\holochain\dev-camp-playground\day2\dna-src\test\node_modules\tape\lib\test.js:226:54)
          at Test.bound [as _assert] (D:\holochain\dev-camp-playground\day2\dna-src\test\node_modules\tape\lib\test.js:77:32)
          at Test.fail (D:\holochain\dev-camp-playground\day2\dna-src\test\node_modules\tape\lib\test.js:319:10)
          at Test.bound [as fail] (D:\holochain\dev-camp-playground\day2\dna-src\test\node_modules\tape\lib\test.js:77:32)
          at scenario.runTape (D:\holochain\dev-camp-playground\day2\dna-src\test\index.js:115:7)
  ...
Stopping instance "alice"...

1..15
# tests 15
# pass  14
# fail  1

Error: command node test/index.js was not successful
```

**Comment by Connoropolous** [comment]
Me too @petersgrandadventure ! It bugs me. 

That's why all the tests in dev-camp-tests-rust were wrapped in try/catch statements, but that's a pain, and should be unnecessary!

This is more good feedback, and evidence of that
