### ISSUE TITLE
Error in p2p network module

### ISSUE THREAD

**Issue by pythagorean** [holochain/holochain-rust#1070]
When running my app with hc, it works, but when using the holochain conductor with n3h, I am getting failures. Here is the output (excerpted):

```
(@hackmode@) [t] Received IPC:  {"name":"json","data":{"method":"publishMeta","dnaAddress":"QmRXd7iA3QZaFTCrL4s54YAZkQeEezkxYpJSz18EeHWW71","providerAgentId":"HoloTester1-----------------------------------------------------------------------AAACZp4xHB","entryAddress":"QmNiSaW14GmxyidHyr2kK2kGMeWzPNj8JtamrGdmzWbcTi","attribute":"link","contentList":[{"entry":{"LinkAdd":{"action_kind":"ADD","link":{"base":"QmNiSaW14GmxyidHyr2kK2kGMeWzPNj8JtamrGdmzWbcTi","target":"QmNNrWCK3RJLh9sZwtLVCTFKSRS6fE2PeMwDYq33JGsRgj","tag":"anchor_link"}}},"header":{"entry_type":"LinkAdd","entry_address":"QmUqa5WougFbU5rXFHS7qoZCYz3UMipmiwbcHTYE66tLaN","provenances":[["HoloTester1-----------------------------------------------------------------------AAACZp4xHB","TODO"]],"link":"Qmd13WdwpKaq7RT1FdZ8guAgPBEJfsThVr8SbBpz4kuJqu","link_same_type":null,"link_crud":null,"timestamp":"1970-01-01T00:00:00+00:00"}}]},"fromZmqId":"00800041a7"}
Strict Fail on Unhandled Promise Rejection
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at getHash (/Users/mahakal/Development/Apps/n3h/packages/hackmode/lib/mem.js:16:24)
    at N3hHackMode._metaIdFromTuple (/Users/mahakal/Development/Apps/n3h/packages/hackmode/lib/index.js:840:27)
    at N3hHackMode._handleIpcMessage (/Users/mahakal/Development/Apps/n3h/packages/hackmode/lib/index.js:233:31)
    at _ipc.on.opt (/Users/mahakal/Development/Apps/n3h/packages/hackmode/lib/index.js:80:41)
    at Promise.all._events.(anonymous function).map.fn (/Users/mahakal/Development/Apps/n3h/packages/n3h-common/lib/async-class.js:129:14)
    at Array.map (<anonymous>)
    at IpcServer.emit (/Users/mahakal/Development/Apps/n3h/packages/n3h-common/lib/async-class.js:128:43)
    at IpcServer._handleMessage (/Users/mahakal/Development/Apps/n3h/packages/n3h-ipc/lib/server.js:180:12)
    at exports.Socket._socket.on.args (/Users/mahakal/Development/Apps/n3h/packages/n3h-ipc/lib/server.js:39:12)
2019-03-01 16:34:52:coolcats2 instance 1: debug/workflow/authoring_entry/QmPbFqpkvaJrGR4godD4WMfopEyVuKSJQqj22zjbtBZV1r: validating...
2019-03-01 16:34:52:coolcats2 instance 1: Authoring entry QmPbFqpkvaJrGR4godD4WMfopEyVuKSJQqj22zjbtBZV1r: is valid!
2019-03-01 16:34:52:coolcats2 instance 1: debug/workflow/authoring_entry/QmPbFqpkvaJrGR4godD4WMfopEyVuKSJQqj22zjbtBZV1r: committing...
2019-03-01 16:34:52:coolcats2 instance 1: debug/workflow/authoring_entry/QmPbFqpkvaJrGR4godD4WMfopEyVuKSJQqj22zjbtBZV1r: committed
2019-03-01 16:34:52:coolcats2 instance 1: debug/workflow/authoring_entry/QmPbFqpkvaJrGR4godD4WMfopEyVuKSJQqj22zjbtBZV1r: publishing...
2019-03-01 16:34:52:coolcats2 instance 1: debug/workflow/authoring_entry/QmPbFqpkvaJrGR4godD4WMfopEyVuKSJQqj22zjbtBZV1r: published!
2019-03-01 16:34:52:coolcats2 instance 1: debug/workflow/authoring_entry: QmNn52grDBMBJqjZRWSrMLeof7SAGCxFCk53z2wikuYg8u with content: LinkAdd(LinkData { action_kind: ADD, link: Link { base: HashString("QmRFWc9zA4t5XNfS6iqirVzMLNcsKd4DAhdQVFZwASDRgc"), target: HashString("QmPbFqpkvaJrGR4godD4WMfopEyVuKSJQqj22zjbtBZV1r"), tag: "anchor_link" } })
2019-03-01 16:34:52:coolcats2 instance 1: debug/workflow/authoring_entry/QmNn52grDBMBJqjZRWSrMLeof7SAGCxFCk53z2wikuYg8u: validating...
2019-03-01 16:34:53:coolcats2 instance 1: Authoring entry QmNn52grDBMBJqjZRWSrMLeof7SAGCxFCk53z2wikuYg8u: is valid!
2019-03-01 16:34:53:coolcats2 instance 1: debug/workflow/authoring_entry/QmNn52grDBMBJqjZRWSrMLeof7SAGCxFCk53z2wikuYg8u: committing...
2019-03-01 16:34:53:coolcats2 instance 1: debug/workflow/authoring_entry/QmNn52grDBMBJqjZRWSrMLeof7SAGCxFCk53z2wikuYg8u: committed
2019-03-01 16:34:53:coolcats2 instance 1: debug/workflow/authoring_entry/QmNn52grDBMBJqjZRWSrMLeof7SAGCxFCk53z2wikuYg8u: publishing...
2019-03-01 16:34:53:coolcats2 instance 1: debug/reduce/link_meta: Publishing link meta for link: Link { base: HashString("QmRFWc9zA4t5XNfS6iqirVzMLNcsKd4DAhdQVFZwASDRgc"), target: HashString("QmPbFqpkvaJrGR4godD4WMfopEyVuKSJQqj22zjbtBZV1r"), tag: "anchor_link" }
2019-03-01 16:34:53:coolcats2 instance 1: debug/workflow/authoring_entry/QmNn52grDBMBJqjZRWSrMLeof7SAGCxFCk53z2wikuYg8u: published!
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
```

**Comment by pythagorean** [comment]
I tried using N3H without the conductor by invoking `HC_N3H_PATH=`pwd`/../../n3h hc run --port 8888` and I get the same errors.

```
(@hackmode@) [t] Received IPC:  {"name":"json","data":{"method":"publishMeta","dnaAddress":"QmUQEfmBWZMhft7jiEvE8Vz7CMuuJ8TVE4NcxXcx17m9jU","providerAgentId":"testAgent-------------------------------------------------------------------------AAABSEVpLS","entryAddress":"testAgent-------------------------------------------------------------------------AAABSEVpLS","attribute":"link","contentList":[{"entry":{"LinkAdd":{"action_kind":"ADD","link":{"base":"testAgent-------------------------------------------------------------------------AAABSEVpLS","target":"QmZ3Lbv8a92Mez81WznYpBdrU9TCtL9JGATUJAnX9QMgSz","tag":"first_name"}}},"header":{"entry_type":"LinkAdd","entry_address":"QmZ41bg4ztDae8nLeAuaiX6J7Ga6Yg1ipzAxyuQtg9X86S","provenances":[["testAgent-------------------------------------------------------------------------AAABSEVpLS","TODO"]],"link":"QmVSqghtfi5b2cQ6dE2v8R7R9mRAJVPcU1ZsEkjkVqkBNy","link_same_type":null,"link_crud":null,"timestamp":"1970-01-01T00:00:00+00:00"}}]},"fromZmqId":"00800041a7"}
Strict Fail on Unhandled Promise Rejection
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:202:9)
    at getHash (/Users/mahakal/Development/Apps/n3h/packages/hackmode/lib/mem.js:16:24)
    at N3hHackMode._metaIdFromTuple (/Users/mahakal/Development/Apps/n3h/packages/hackmode/lib/index.js:840:27)
    at N3hHackMode._handleIpcMessage (/Users/mahakal/Development/Apps/n3h/packages/hackmode/lib/index.js:233:31)
    at _ipc.on.opt (/Users/mahakal/Development/Apps/n3h/packages/hackmode/lib/index.js:80:41)
    at Promise.all._events.(anonymous function).map.fn (/Users/mahakal/Development/Apps/n3h/packages/n3h-common/lib/async-class.js:129:14)
    at Array.map (<anonymous>)
    at IpcServer.emit (/Users/mahakal/Development/Apps/n3h/packages/n3h-common/lib/async-class.js:128:43)
    at IpcServer._handleMessage (/Users/mahakal/Development/Apps/n3h/packages/n3h-ipc/lib/server.js:180:12)
    at exports.Socket._socket.on.args (/Users/mahakal/Development/Apps/n3h/packages/n3h-ipc/lib/server.js:39:12)
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
Error occured in p2p network module: ErrorMessage { msg: "[puid-1-0] ipc connection timeout" }
```

**Comment by pythagorean** [comment]
This is 0.0.4-alpha.

**Comment by pythagorean** [comment]
Upgrading N3H to the v0.0.4-alpha1 version fixed this problem.
