### ISSUE TITLE
holochain-nodejs build issue

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#1127]
https://realtimeboard.com/app/board/o9J_kyiXmFs=/?moveToWidget=3074457346519547752

Holochain-rust core build question.  I'm using shell.nix, now, and I am presuming that the following list of commands is what I need to do to build the core:
```
nix-shell --run hc-build-wasm
nix-shell --run hc-install-cli
nix-shell --run hc-install-conductor
nix-shell --run hc-install-node-conductor
However, the build of hc-install-node-conductor is failing with:

node-pre-gyp info using node@8.15.0 | linux | x64
node-pre-gyp info package Binary staged at "build/stage/holochain-nodejs-v0.4.5-alpha/index-v0.4.5-alpha-node-v57-linux-x64.tar.gz"
node-pre-gyp info ok
./build/stage/holochain-nodejs-v0.4.2-alpha/index-v0.4.2-alpha-node-v64-linux-x64.tar.gz
./build/stage/holochain-nodejs-v0.4.2-alpha/index-v0.4.2-alpha-node-v57-linux-x64.tar.gz
./build/stage/holochain-nodejs-v0.4.5-alpha/index-v0.4.5-alpha-node-v57-linux-x64.tar.gz
./build/stage/holochain-nodejs-v0.4.4-alpha/index-v0.4.4-alpha-node-v57-linux-x64.tar.gz
./build/stage/holochain-nodejs-v0.4.4-alpha/index-v0.4.4-alpha-node-v64-linux-x64.tar.gz
/home/perry/src/holochain-rust/nodejs_conductor/node_modules/shelljs/src/common.js:401
      if (config.fatal) throw e;
                        ^

Error: cp: no such file or directory: ./build/stage/holochain-nodejs-v0.4.2-alpha/index-v0.4.2-alpha-node-v64-linux-x64.tar.gz
./build/stage/holochain-nodejs-v0.4.2-alpha/index-v0.4.2-alpha-node-v57-linux-x64.tar.gz
./build/stage/holochain-nodejs-v0.4.5-alpha/index-v0.4.5-alpha-node-v57-linux-x64.tar.gz
./build/stage/holochain-nodejs-v0.4.4-alpha/index-v0.4.4-alpha-node-v57-linux-x64.tar.gz
./build/stage/holochain-nodejs-v0.4.4-alpha/index-v0.4.4-alpha-node-v64-linux-x64.tar.gz

    at Object.error (/home/perry/src/holochain-rust/nodejs_conductor/node_modules/shelljs/src/common.js:110:27)
    at /home/perry/src/holochain-rust/nodejs_conductor/node_modules/shelljs/src/cp.js:242:14
    at Array.forEach (<anonymous>)
    at Object._cp (/home/perry/src/holochain-rust/nodejs_conductor/node_modules/shelljs/src/cp.js:239:11)
    at Object.cp (/home/perry/src/holochain-rust/nodejs_conductor/node_modules/shelljs/src/common.js:384:25)
    at Object.<anonymous> (/home/perry/src/holochain-rust/nodejs_conductor/publish.js:75:7)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
```

That's a bug, and it needs fixing. It will be resolved, I believe, by deleting a folder on your comp: nodejs_conductor/build
Then re-run the failing command

OK, thanks.  I'm revising the Makefile to just target nix-shell --run ..., so I'll add that to the build target.

The bug is something of a regression, it was introduced here, and should possibly /likely be fixed here: https://github.com/holochain/holochain-rust/commit/0d09c26c3a060c7466527c92c4f4130b10b73065

**Comment by jamesray1** [comment]
This looks outdated. 0d09c26 was merged in #1072. We are using `nix-shell https://holochain.love`. Not sure if this is still relevant, but I got another issue with nix-shell --run hc-build-wasm.

```
[jr@lm ~]$ cd hcr
[jr@lm hcr]$ nix-shell --run hc-build-wasm
bash: nix-shell: command not found
➜  ~ nix-shell --run
error: '--run' requires an argument
```
I am currently running `nix-shell --run hc-install-cli` but it is building from scratch.

I suggest to close?
