### ISSUE TITLE
bad n3h install on osx

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-rust#1268]
Running https://github.com/Connoropolous/ready-chat-mac-electron

And seeing this in `~/Library/Logs/basic-chat/log.log`

macosx

```
[2019-04-15 14:02:12.199] [info] Using config path: ./conductor-config.toml
Unlocking agent keys:
Unlocking key for agent 'test_agent1': 
Reading keystore from ./keystore.key

[2019-04-15 14:02:28.246] [info] Spawning network with working directory: /tmp

[2019-04-15 14:02:28.255] [info] response: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

[2019-04-15 14:02:28.258] [info] response: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })

[2019-04-15 14:02:50.509] [info] Error while spawning network process: ErrorMessage { msg: "bad exit Some(16) \"hdiutil: couldn\\\'t unmount \\\"disk3\\\" - Resource busy\\n\"" }

[2019-04-15 14:02:50.516] [info] Reading DNA from dna/holo-chat.dna.json

[2019-04-15 14:02:50.556] [info] Failed to load instance holo-chat from storage: ErrorGeneric("State could not be loaded due to NoneError")
Initializing new chain...

[2019-04-15 14:02:51.587] [error] thread '<unnamed>' panicked at 'ErrorMessage { msg: "config.spawn or config.ipcUri is required" }', net/src/connection/net_connection_thread.rs:51:73
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

[2019-04-15 14:02:51.589] [error] thread '<unnamed>' panicked at 'Failed to receive endpoint address from net worker: RecvError', src/libcore/result.rs:997:5
```

**Comment by jamesray1** [comment]
Note that https://github.com/Connoropolous/ready-chat-mac-electron gives me a 404, so I can't repro, and given that this is an old issue it may have been resolved. Nevertheless, trying to look into it as follows:

`Spawning network with working directory: /tmp`

comes from

https://github.com/holochain/holochain-rust/blob/a1100e3225b8315a6fc45a36d0d3b9558ad37398/crates/conductor_lib/src/conductor/base.rs#L556

Looking further at that code:

https://github.com/holochain/holochain-rust/blob/a1100e3225b8315a6fc45a36d0d3b9558ad37398/crates/conductor_lib/src/conductor/base.rs#L548-L588

ipc_spawn

https://github.com/holochain/holochain-rust/blob/aa53657ee25bd35304c177a8d5560318644b0ccf/crates/net/src/ipc/spawn.rs#L25-L34

load_end_user_config doesn't look like it would cause

`response: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" }).`

https://github.com/holochain/holochain-rust/blob/aa53657ee25bd35304c177a8d5560318644b0ccf/crates/net/src/p2p_config.rs#L270-L272

I spent a while looking, but to avoid potentially wasting time if this bug is resolved, could you let me know if you still have access to https://github.com/Connoropolous/ready-chat-mac-electron, and whether you can reproduce?

**Comment by Connoropolous** [comment]
Don't worry about it :) old issue.
