### ISSUE TITLE
Conductor hangs & thrashes CPU when running tests

### ISSUE THREAD

**Issue by pospi** [holochain/holochain-rust#1662]
Hard to say whether this is a https://github.com/holochain/diorama issue or a core issue, but presumably the fact that it's possible to create this error condition warrants investigation in core.

[My setup](https://github.com/holo-rea/holo-rea/tree/feature/nix-install-scripts#setup) is completely reproducible and uses latest Holonix (`0.0.29`). The failing test is [located here](https://github.com/holo-rea/holo-rea/blob/95be52e/test/core-architecture/test_update_behavior.js#L10) and can be executed with `npx tape test/core-architecture/test_update_behavior.js` from within that Nix environment. When run, this yields the following:

```
TAP version 13
# updates with fields ommitted leave original value intact
info: Test over, waiting for Waiter to flush...
info: conductor pool size: 0
info: using port
info: Using config file at /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/conductor-config.toml
info: Using holochain binary at /nix/store/5dsdc60gfc51a0vabbsfv1ivqw2lv0p8-holochain/bin/holochain

info: test conductor spawned
info: [C] Using config path: /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/conductor-config.toml
Unlocking agent keys:
Successfully loaded 0 instance configurations
Starting instances...
Starting interfaces...

info: [C] Done.
Starting UI servers
Starting all servers

info: test conductor connected to admin interface
info: using port
info: [C] Starting interface 'test-interface-34763'.

info: [C] Added agent "observation"

info: [C] Reading DNA from /home/pospi/projects/holo-rea/oce-holo/happs/observation/dist/observation.dna.json

info: [C] Installed DNA from /home/pospi/projects/holo-rea/oce-holo/happs/observation/dist/observation.dna.json as "observation-3"

info: [C] Reading DNA from /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/dna/Qme3MiDhHner7YMFRfzRgVa6ZWLSKhU9C9guBRY49v2HJF.dna.json

info: [C] Reading DNA from /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/dna/Qme3MiDhHner7YMFRfzRgVa6ZWLSKhU9C9guBRY49v2HJF.dna.json

info: [C] Reading DNA from /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/dna/Qme3MiDhHner7YMFRfzRgVa6ZWLSKhU9C9guBRY49v2HJF.dna.json

info: [C] Reading DNA from /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/dna/Qme3MiDhHner7YMFRfzRgVa6ZWLSKhU9C9guBRY49v2HJF.dna.json

info: [C] Failed to load instance observation-3 from storage: ErrorGeneric("State could not be loaded due to NoneError")
Initializing new chain...

info: [C] register_chain: Qme3MiDhHner7YMFRfzRgVa6ZWLSKhU9C9guBRY49v2HJF::HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si
JOINING SPACE: dna(Qme3MiDhHner7YMFRfzRgVa6ZWLSKhU9C9guBRY49v2HJF), agent(HcSCjHmVuZKrg7rgvrz7uBxHpkf3ncmvfnWU3HFgzYjd9w7rxihu4Bh3ztug9si)

info: [C] Reading DNA from /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/dna/Qme3MiDhHner7YMFRfzRgVa6ZWLSKhU9C9guBRY49v2HJF.dna.json

info: [C] Stopping interface test-interface-34763

info: [C] Starting interface 'test-interface-34763'.

info: [C] Starting instance "observation-3"...

ok 1 record created successfully
error: Test failed while running: "zome call timed out after 60 seconds: observation-3/economic_event/get_event"
not ok 2 (unnamed assert)
  ---
    operator: fail
    at: run.catch (/home/pospi/projects/holo-rea/oce-holo/node_modules/@holochain/diorama/lib/executors.js:18:19)
    stack: |-
      Error: (unnamed assert)
          at Test.assert [as _assert] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:224:54)
          at Test.bound [as _assert] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:76:32)
          at Test.fail (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:317:10)
          at Test.bound [as fail] (/home/pospi/projects/holo-rea/oce-holo/test/node_modules/tape/lib/test.js:76:32)
          at run.catch (/home/pospi/projects/holo-rea/oce-holo/node_modules/@holochain/diorama/lib/executors.js:18:19)
  ...
# updates with fields nulled remove original value
info: Test over, waiting for Waiter to flush...
vvvv    hachiko warning    vvvv
a hachiko callback has been waiting for 16 seconds with no change
Still waiting on the following 1 signal(s):
[ { event: '{"ReturnZomeFunctionResult":{"prefix":9,"offset":89}}',
    sourceNode: 'observation',
    targetNode: 'observation' } ]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^[[Dvvvv  hachiko timed out!  vvvv
Still waiting on the following 1 signal(s):
[ { event: '{"ReturnZomeFunctionResult":{"prefix":9,"offset":89}}',
    sourceNode: 'observation',
    targetNode: 'observation' } ]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/pospi/projects/holo-rea/oce-holo/node_modules/@holochain/hachiko/lib/waiter.js:28
                throw new Error("hachiko timeout!!");
                ^

Error: hachiko timeout!!
    at Timeout._onTimeout (/home/pospi/projects/holo-rea/oce-holo/node_modules/@holochain/hachiko/lib/waiter.js:28:23)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
```

Looking at my process list immediately afterwards, and about 30 seconds following:

```
[nix-shell:~/projects/holo-rea/oce-holo]$ ps aux | grep holo
pospi    11703  1.5  0.4 1594668 140884 ?      Ssl  16:54   1:13 /usr/share/code/code /home/pospi/Documents/holo-rea.code-workspace
pospi    16553  0.0  0.0  10956   948 pts/0    S    16:58   0:00 sh -c nix-shell holonix-0.0.29
pospi    22499 99.9  0.5 1583668 178664 pts/0  SLl  18:13   2:17 holochain -c /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/conductor-config.toml
pospi    23318  0.0  0.0   7228  2264 pts/0    S+   18:15   0:00 grep --color=auto holo

[nix-shell:~/projects/holo-rea/oce-holo]$ ps aux | grep holo
pospi    11703  1.5  0.4 1594668 140884 ?      Ssl  16:54   1:13 /usr/share/code/code /home/pospi/Documents/holo-rea.code-workspace
pospi    16553  0.0  0.0  10956   948 pts/0    S    16:58   0:00 sh -c nix-shell holonix-0.0.29
pospi    22499  100  0.5 1583668 178664 pts/0  SLl  18:13   2:42 holochain -c /tmp/tmp.ze3agIDHaB/hc-diorama-wOVrFM/conductor-config.toml
pospi    23428  0.0  0.0   7228   588 pts/0    S+   18:16   0:00 grep --color=auto holo
```

The process seemingly won't die on its own or with a nudge... needs a `kill -9`.

Nothing crazy in the [API handler](https://github.com/holo-rea/holo-rea/blob/ac5299b/happs/observation/zomes/economic_event/code/src/economic_event_requests.rs#L40), and it was working fine on `0.0.18`.

**Comment by pospi** [comment]
More testing: booting a normal conductor (`npm run dht` from within that repo, if anyone is pulling it down to reproduce) seems to work fine- I can poke the system with `create_event`, `update_event` and `get_event` just fine if done manually. So may be a Diorama issue after all.

**Comment by pospi** [comment]
Ignore "it was working fine on `0.0.18`" in the above, looks like I have my own evidence of this being an issue prior to the current version (see https://github.com/holochain/diorama/issues/11).

**Comment by pospi** [comment]
I think I figured out what this relates to exactly- updating an entry where the new entry data is the same as the previous entry data seems to cause the DNA to go into an infinite loop any time accessing the entry data is attempted thereafter.

I feel as though this should be a check that gets pushed down into core, so the app developer doesn't have to think about it?

**Comment by pospi** [comment]
Found another way of reproducing this which I think begins to make the issue clearer.

- When one updates an entry with the same content as its existing content, this causes an infinite loop when attempting to read that entry (as above; presumably due to cyclic walking of the entry update metadata).
- When one updates a previously updated entry with different content (so, the stale address is provided to `update_entry` rather than the most recent address), this causes an infinite loop if attempting to read that entry using an address that was previously used to identify the entry before the update loop was created.

**Comment by pospi** [comment]
According to @philipbeadle this was fixed in the latest release, but I still encounter the bug if I revert https://github.com/holo-rea/holo-rea/commit/482f80c and https://github.com/holo-rea/holo-rea/commit/796acf2. This is using `v0.0.30-alpha6`.
