### ISSUE TITLE
container.call() error: No instance with id: alice::dist/bundle.json

### ISSUE THREAD

**Issue by marcusnewton1** [holochain/holochain-rust#859]
Having trouble running `hc test` with latest preview release (holochain-rust v0.0.3 and holochain-nodejs v0.3.0). Edit: Windows 10

[repo for my app](https://github.com/OmniProject/omni/tree/v0.0.3-testing)

test/index.js:
```
const test = require('tape')
const { Config, Container } = require('@holochain/holochain-nodejs')

const dnaPath = "dist/bundle.json"
const dna = Config.dna(dnaPath)

const aliceName = "alice"
const tashName = "tash"

const agentAlice = Config.agent(aliceName)
const agentTash = Config.agent(tashName)
const instanceAlice = Config.instance(agentAlice, dna)
const instanceTash = Config.instance(agentTash, dna)

const config = Config.container([instanceAlice, instanceTash])

const container = new Container(config)

const aliceInstanceId = aliceName + '::' + dnaPath
const tashInstanceId = tashName + '::' + dnaPath

test('create an article', (t) => {
  t.plan(2)

  const input = {
    article: {
      title: "Article Title",
      abst: "abstract text",
      body: "body of article"
    }
  }

  const expect = {
    "success": true
  }

  const result = container.call(aliceInstanceId, "articles", "main", "create_article", input)

  console.log(result);

  t.deepEqual(result.success, expect.success)
  t.deepEqual(result.address.length, 46)

  t.end()
})

// stop all running instances
container.stop()
```

Output:
```
> node test/index.js
TAP version 13
# create an article
C:\Users\marcu\Documents\GitHub\omni\test\node_modules\@holochain\holochain-nodejs\index.js:15
    const rawResult = this.callRaw(id, zome, trait, fn, stringInput);
                           ^

Error: internal error in Neon module: No instance with id: alice::dist/bundle.json
    at NodeContainer.Container.call (C:\Users\marcu\Documents\GitHub\omni\test\node_modules\@holochain\holochain-nodejs\index.js:15:28)
    at Test.test (C:\Users\marcu\Documents\GitHub\omni\test\index.js:39:28)
    at Test.bound [as _cb] (C:\Users\marcu\Documents\GitHub\omni\test\node_modules\tape\lib\test.js:76:32)
    at Test.run (C:\Users\marcu\Documents\GitHub\omni\test\node_modules\tape\lib\test.js:95:10)
    at Test.bound [as run] (C:\Users\marcu\Documents\GitHub\omni\test\node_modules\tape\lib\test.js:76:32)
    at Immediate.next (C:\Users\marcu\Documents\GitHub\omni\test\node_modules\tape\lib\results.js:71:15)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Error: command node test/index.js was not successful
```

**Comment by maackle** [comment]
@marcusnewton1 that is a misleading error that I ran into once as well. It can mean that you're referring to the wrong instance ID, but it looks like you've got that all correct. It can also show up when the container did not initialize properly. I ran into this problem when I had the wrong DNA path. Could you check that the file referenced in your `dnaPath` exists?

**Comment by marcusnewton1** [comment]
@maackle path to DNA is correct

**Comment by maackle** [comment]
@marcusnewton1 I am still not sure what this could be, but if you'd like to help debug, could you try using an absolute path for `dnaPath`? Maybe the relative path is not resolving right?

If that doesn't work, you might also try starting a `holochain_container` instance configured to use this dna and see if that also doesn't work, and perhaps it will give more information.

**Comment by marcusnewton1** [comment]
@maackle Sure. Not seeing any difference using an absolute path. `Error: internal error in Neon module: No instance with id: alice::~/Google Drive/GitHub/Omni/dist/bundle.json`

I've got holochain_container installed and working, no clue how to use it though

**Comment by marcusnewton1** [comment]
It would really help if we had documentation for the container

**Comment by marcusnewton1** [comment]
I rolled back to holochain-nodejs version 0.2.0 and used my original working tests script and I get the error `Unable to create Holochain instance`. This may just be a compatibility error with hc v0.0.3.

```
$ hc test
Packaging files for testing to file: "C:\\Users\\marcu\\Documents\\GitHub\\omni\\dist\\bundle.json"
> cargo build --release --target=wasm32-unknown-unknown
    Finished release [optimized] target(s) in 0.31s
> cargo build --release --target=wasm32-unknown-unknown
    Finished release [optimized] target(s) in 0.28s
Created bundle file at "C:\\Users\\marcu\\Documents\\GitHub\\omni\\dist\\bundle.json"
Running tests in test/index.js
> node test/index.js
Unable to create Holochain instance
C:\Users\marcu\Documents\GitHub\omni\test\node_modules\@holochain\holochain-nodejs\index.js:22
          throw e;
          ^

Error: internal error in Neon module: unable to parse dna data: SerializationError("missing field `code` at line 1 column 2461443")
    at Object.instanceFromNameAndDna (C:\Users\marcu\Documents\GitHub\omni\test\node_modules\@holochain\holochain-nodejs\index.js:19:17)
    at Object.loadAndInstantiate (C:\Users\marcu\Documents\GitHub\omni\test\node_modules\@holochain\holochain-nodejs\index.js:53:27)
    at Object.<anonymous> (C:\Users\marcu\Documents\GitHub\omni\test\index.js:10:29)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
Error: command node test/index.js was not successful
```

**Comment by marcusnewton1** [comment]
Closing issue because original error `No instance with id: alice::dist/bundle.json` is resolved because I forgot to do `container.start()` before making calls, however I am still having problems with `container.start()`

```
container.start()
          ^
unable to start container: Error while trying to create instance "alice::dist/bundle.json": Could not load DNA file "dist/bundle.json"
```

See #870
