### ISSUE TITLE
hc test failed: Config.conductor is not a function

### ISSUE THREAD

**Issue by rairyx** [holochain/holochain-rust#963]
When running hc test for a zome, it failed with error:

 /home/rai/play/holo/hello/test/index.js:17
    const conductorConfig = Config.conductor([instanceAlice])
                                   ^

TypeError: Config.conductor is not a function
    at /home/rai/play/holo/hello/test/index.js:17:36
    at Object.<anonymous> (/home/rai/play/holo/hello/test/index.js:19:3)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
    at Function.Module._load (internal/modules/cjs/loader.js:558:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:797:12)
    at executeUserCode (internal/bootstrap/node.js:526:15)
    at startMainThreadExecution (internal/bootstrap/node.js:439:3)
Error: command node test/index.js was not successful

**Comment by petersgrandadventure** [comment]
I am also getting this, on my ubuntu on windows setup.

**Comment by petersgrandadventure** [comment]
I don't have this problem with 0.0.4

**Comment by rairyx** [comment]
Cool I'll give it a try, thanks!
